import image from "@/public/revealing.png"

const boardMembers = [
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: image,
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  
  
];
export default boardMembers;