const boardMembers = [
  {
    name: "XYZ",
    image: "/revealing.png",
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: "/revealing.png",
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: "/revealing.png",
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: "/revealing.png",
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: "/revealing.png",
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: "/revealing.png",
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  {
    name: "XYZ",
    image: "/revealing.png",
    role: "XYZ",
    description: "Placeholder",
    github: "",
    linkedIn: "",
    type: "organizer",
  },
  
];
export default boardMembers;